image: Visual Studio 2017

build_script:
  - ps: .\build.ps1 -Target "Appveyor"

# disable built-in tests.
test: off

deploy:
- provider: NuGet
  server: https://www.myget.org/F/commercetools-dotnet-sdk/api/v2/package
  api_key:
    secure: +Pfl0dfkKW+5dZY/6vRFGLhE3pOd3xMTz1v7ARA8hgrtUVwnl4BdnW1hHTg1df+d
  skip_symbols: true
  on:
    branch: master
